### ISSUE TITLE
Make registry operations production-ready

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-windows#39]
The `Ensure-RegistryXYZ` operations already exist (and can be searched in the plan editor), but need `DisplayName`, `Tag`, and `Example`  attributes for completeness.

Also, the `Advanced` tab is sorted before `General` in the `Ensure-RegistryValue` operation.

**Comment by BenLubar** [comment]
> Also, the `Advanced` tab is sorted before `General` in the `Ensure-RegistryValue` operation.

On my instance, there are no tabs in the editor for any registry-related ensure operations.
