### ISSUE TITLE
Unexpected error when save a Ensure-RegistryValue in visual Mode on IIS 10.0 server 

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-windows#43]
Hello
Saving a Ensure-RegistryValue in visual mode results an unexpected error when saving whereas texte mode works fine.
```
Windows::Ensure-RegistryValue
(
    Name: AllowTelemetry,
    Value: 0,
    Hive: LocalMachine,
    Key: SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection
);
```

**Comment by gdivis** [comment]
Thanks - we'll look into this and see if we can reproduce it.

**Comment by BenLubar** [comment]
Is there any message in the error log? I can't reproduce this locally.

**Comment by pcamelio** [comment]
Hi
I did not find any error log.
Here is the exact message 
``An unexpected error occured while posting to the server
Internal Server Error
You should try to save your work if possible
``
I am using the IIS server and not the embed HTTP server.

**Comment by BenLubar** [comment]
Ok, I was able to reproduce and fix it.
