### ISSUE TITLE
Internal Server Error when saving Ensure DSC in GUI mode

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-windows#62]
Hello
I tried to use the Ensure-DSC.
Creation in gui mode the hdars text sample unsuccessuffly. I have got an Internal error when I save it..
I change to text mode, I wrote 
```
 {
    Ensure-DscResource
    (
        Name: File,
        ConfigurationKey: DestinationPath,
        Properties: %(
    DestinationPath: C:\hdars\1000.txt,
    Contents: test file ensured)
    );
}
```
Save and force an autoremediate and it is working fine.
I went back to the GUI mode:

- edition of the Ensure-DSC, 

- modification of _properties_ and again "Internal Error"

Regards
Philippe

**Comment by gdivis** [comment]
Hi Philippe,

It looks like this is actually an error in BuildMaster itself - I've logged it as [SDK-28](https://github.com/Inedo/inedox-windows/issues/62), and it will be fixed in the next release.

**Comment by gdivis** [comment]
I meant to say in Otter and BuildMaster - it affects both products.

**Comment by pcamelio** [comment]
Hello gdivis,
it seems not a lot of people try this new feature.
I'll still use PsDSC until the next release. 
Regards
