### ISSUE TITLE
Add SuccessExitCode to PSExec and PSCall

### ISSUE THREAD

**Issue by whatatripp** [Inedo/inedox-windows#73]
This should be identical to Execute Process, except that it should default to null as to keep with current behavior.

`SuccessExitCode`

**Success exit code**. Integer exit code which indicates no error. The default is empty, which means that the error code will not be used to evaluate success. This can also be an integer prefixed with an inequality operator (e.g. ">=0" or "<5").

**Comment by BenLubar** [comment]
For PSCall, this is tougher, since PSCall already passes the entire argument space to the PowerShell process. Deferring PSCall support for SuccessExitCode pending further discussion.
